### ISSUE TITLE
Local fetch does not work correctly

### ISSUE THREAD

**Issue by djmaze** [djmaze/swm#1]
`swm cluster fetch --local` returns `0.0.0.0` as the address of one of my local servers.

**Comment by feueraustreter** [comment]
Others also have this problem with their tools. Here you may find some useful hints:
[Swarmpit - Wrong IP address for manager leader](https://github.com/swarmpit/swarmpit/issues/476) and [Moby - Docker swarm ip addr 0.0.0.0](https://github.com/moby/moby/issues/35437)

Torsten

**Comment by djmaze** [comment]
Thanks!
