### ISSUE TITLE
Build fails using crystal 0.35.1 on macOS 10.15.5

### ISSUE THREAD

**Issue by feueraustreter** [djmaze/swm#8]
Hi Martin,

using crystal 0.35.1 the swm (master) build fails (on macOS 10.15.5 but I don't think it is related to MacOS):

```
% shards build
Dependencies are satisfied
Building: swm
Error target swm failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/docker/ssh_docker_executor.cr:17:17

 17 | process = fork do
                ^---
Error: undefined local variable or method 'fork' for Swm::SSHDockerExecutor
```

Same problem with release version 0.1.3:
```
% shards build
Dependencies are satisfied
Building: swm
Error target swm failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/docker/client.cr:57:17

 57 | process = fork do
                ^---
Error: undefined local variable or method 'fork' for Swm::DockerClient
```

I use this this crystal version:
```
% crystal --version
Crystal 0.35.1 (2020-06-19)

LLVM: 10.0.0
Default target: x86_64-apple-macosx

% shards --version 
Shards 0.11.1 (2020-07-04)
```

After switching to crystal 0.34.0 everything was fine.

```
% crystal --version
Crystal 0.34.0 (2020-04-07)

LLVM: 10.0.0
Default target: x86_64-apple-macosx

% shards --version 
Shards 0.10.0 (2020-04-07)
```

When I look at  [crystal release 0.35.0](https://github.com/crystal-lang/crystal/releases/tag/0.35.0), I may have found something that could be related to the problem. Unfortunately, I've never used crystal before.

```
Runtime
(breaking-change) Deprecate top-level fork. (#9136, thanks @bcardiff)
```

Thank you
Torsten

**Comment by djmaze** [comment]
Yes, in the latest version Crystal removed the`fork` method, because it is not multi-thread friendly (which is the new default runtime mode.)

The code probably needs to be ported to use fibers instead, which will hopefully work as well. I can have a look at that when I find some time.

**Comment by feueraustreter** [comment]
Cool 👍
